version: 2

sources:
  - name: ecommerce
    database: e-commerce-455720
    description: 'Source tables for the business, extracted from the operational database.'
    schema: raw
    tables:

      - name: customers
        description: "This dataset has information about the customer and its location. Use it to identify unique customers in the orders dataset and to find the orders delivery location."
        columns:
          - name: customer_id
            description: "key to the orders dataset. Each order has a unique customer_id."
            data_tests:
              - unique
              - not_null

          - name: customer_unique_id
            description: "unique identifier of a customer."
            data_tests:
              - not_null

          - name: customer_zip_code_prefix
            description: "first five digits of customer zip code"

          - name: customer_city
            description: "The city customer lives"

          - name: customer_state
            description: "The state the customer lives"

          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"
          
                  
      - name: geolocation
        description: "This dataset has information Brazilian zip codes and its lat/lng coordinates. Use it to plot maps and find distances between sellers and customers."
        columns:
          - name: geolocation_zip_code_prefix
            description: "first 5 digits of zip code"
          - name: geolocation_lat
            description: "latitude"
          - name: geolocation_lng
            description: "longitude"
          - name: geolocation_city
            description: "city name"
          - name: geolocation_state
            description: "state name"
          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"
      

      - name: order_items
        description: "This dataset includes data about the items purchased within each order."
        columns:
          - name: order_id
            description: "order unique identifier"
            data_tests:
              - not_null

          - name: order_item_id
            description: "sequential number identifying number of items included in the same order."
            data_tests:
              - not_null

          - name: product_id
            description: "product unique identifier"
            data_tests:
              - not_null

          - name: seller_id
            description: "seller unique identifier"
            data_tests:
              - not_null

          - name: shipping_limit_date
            description: "Shows the seller shipping limit date for handling the order over to the logistic partner."

          - name: price
            description: "item price"
            data_tests:
              - not_null

          - name: freight_value
            description: "item freight value item (if an order has more than one item the freight value is split between items)"
            data_tests:
              - not_null
              
          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"


      - name: order_payments
        description: "This dataset includes data about the orders payment options."
        columns:
          - name: order_id
            description: "unique identifier of an order."
            data_tests:
              - not_null

          - name: payment_sequential
            description: "a customer may pay an order with more than one payment method. If he does so, a sequence will be created"

          - name: payment_type
            description: "method of payment chosen by the customer."
            data_tests:
              - accepted_values:
                  values: ['credit_card', 'voucher', 'boleto', 'debit_card', 'not_defined']

          - name: payment_installments
            description: "number of installments chosen by the customer."
          
          - name: payment_value
            description: "transaction value."
            data_tests:
              - not_null
            
          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"


      - name: order_reviews
        description: "This dataset includes data about the reviews made by the customers."
        columns:
          - name: review_id
            description: "unique review identifier"
            data_tests:
              - not_null

          - name: order_id
            description: "unique order identifier"
            data_tests:
              - not_null

          - name: review_score
            description: "Note ranging from 1 to 5 given by the customer on a satisfaction survey."

          - name: "review_comment_title"
            description: "Comment title from the review left by the customer, in Portuguese."

          - name: review_comment_message
            description: "Comment message from the review left by the customer, in Portuguese."

          - name: review_creation_date
            description: "Shows the date in which the satisfaction survey was sent to the customer."
            data_tests:
              - not_null

          - name: review_answer_timestamp
            description: "Shows satisfaction survey answer timestamp."
            data_tests:
              - not_null

          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"


      - name: orders
        description: "This is the core dataset. From each order you might find all other information."
        columns:
          - name: order_id
            description: "unique identifier of the order."
            data_tests:
              - unique
              - not_null

          - name: customer_id
            description: "key to the customer dataset. Each order has a unique customer_id."
            data_tests:
              - not_null

          - name: order_status
            description: "Reference to the order status (delivered, shipped, etc)."
            data_tests:
              - accepted_values:
                  values: ['delivered', 'invoiced', 'shipped', 'processing', 'unavailable', 'canceled', 'created', 'approved']

          - name: order_purchase_timestamp
            description: "Shows the purchase timestamp."
            data_tests:
              - not_null

          - name: order_approved_at
            description: "Shows the payment approval timestamp."

          - name: order_delivered_carrier_date
            description: "Shows the order posting timestamp. When it was handled to the logistic partner."

          - name: order_delivered_customer_date
            description: "Shows the actual order delivery date to the customer."

          - name: order_estimated_delivery_date
            description: "Shows the actual order delivery date to the customer."

          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"
            
      - name: products
        description: "This dataset includes data about the products sold by the company."
        columns:
          - name: product_id
            description: "unique product identifier"
            data_tests:
              - unique
              - not_null

          - name: product_category_name
            description: "root category of product, in Portuguese."

          - name: product_weight_g
            description: "product weight measured in grams."

          - name: product_length_cm
            description: "product length measured in centimeters."

          - name: product_height_cm
            description: "product height measured in centimeters."

          - name: product_width_cm
            description: "product width measured in centimeters."

          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"

      - name: sellers
        description: "This dataset includes data about the sellers that fulfilled orders made at Olist. Use it to find the seller location and to identify which seller fulfilled each product."
        columns:
          - name: seller_id
            description: "seller unique identifier"
            data_tests:
              - unique
              - not_null

          - name: seller_zip_code_prefix
            description: "first 5 digits of seller zip code"

          - name: seller_city
            description: "seller city name"

          - name: seller_state
            description: "seller state name"

          - name: _fivetran_synced
            description: "The last time fivetran imported or updated this row"